[pytest]
filterwarnings =
    error::DeprecationWarning
    ignore:.*parseString.*deprecated.*:Warning:matplotlib\._fontconfig_pattern
    ignore:.*resetCache.*deprecated.*:Warning:matplotlib\._fontconfig_pattern
    ignore:.*enablePackrat.*deprecated.*:Warning:matplotlib\._mathtext
